### ISSUE TITLE
 Failed to regenerate ASG cache: cannot autodiscover ASGs

### ISSUE THREAD

**Issue by KOSSOKO** [awsdocs/amazon-eks-user-guide#104]
Hi, I follow this documentation in order to set up my K8S cluster and install cluster autoscaler.
I used this command to create my cluster 

```
eksctl create cluster \
--name gara-int-cluster \
--version 1.15  \
--region eu-west-3 \
--nodegroup-name standard-workers \
--node-type t2.micro \
--nodes 3 \
--nodes-min 1 \
--nodes-max 4 \
--ssh-access \
--ssh-public-key gara-cluster-public-eks.pub \
--managed
```
Then I followed the instructions to add cluster autoscaler.
When I check the autoscaler logs at the end, I have this error:

> E0322 18:48:28.135501       1 aws_manager.go:259] Failed to regenerate ASG cache: cannot autodiscover ASGs: AccessDenied: User: arn:aws:sts::849616654863:assumed-role/eksctl-gara-int-cluster-nodegroup-NodeInstanceRole-19QKQO25WZ3M9/i-0ee6bc34b33c65e12 is not authorized to perform: autoscaling:DescribeTags
>         status code: 403, request id: 7a3526a2-0cc6-4377-88a7-b558fb094e77
> F0322 18:48:28.218626       1 aws_cloud_provider.go:351] Failed to create AWS Manager: cannot autodiscover ASGs: AccessDenied: User: arn:aws:sts::849616654863:assumed-role/eksctl-gara-int-cluster-nodegroup-NodeInstanceRole-19QKQO25WZ3M9/i-0ee6bc34b33c65e12 is not authorized to perform: autoscaling:DescribeTags
>         status code: 403, request id: 7a3526a2-0cc6-4377-88a7-b558fb094e77
> goroutine 44 [running]:
> k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog.stacks(0x4cbb001, 0x3, 0xc0004c01e0, 0x17c)
>         /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/klog.go:900 +0xb1
> 

I'm new with AWS. What did I do wrong ? Thanks in advance

**Comment by jimdial-aws** [comment]
Based on the error message, it sounds like the IAM policy was not created or attached to the worker node IAM role that eksctl created for your worker node group when you created your cluster. You can either create a cluster using the --asg-access option, as mentioned in the [Cluster Autoscaler](https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html) topic, or manually create the policy and attach it to your IAM role using the instructions in the [Cluster Autoscaler Node group Considerations](https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html#ca-ng-considerations) section of that same topic. Closing for now, but feel free to re-open if this doesn't solve your issue.
