### ISSUE TITLE
File Does Not Exist

### ISSUE THREAD

**Issue by thomas27G** [awsdocs/amazon-eks-user-guide#115]
With the lastest updates the instructions to pull the following file fails:

https://amazon-eks.s3.us-west-2.amazonaws.com/cloudformation/2020-04-21/dns.yaml

Steps to reproduce:

Run `curl -o dns.yaml https://amazon-eks.s3.us-west-2.amazonaws.com/cloudformation/2020-04-21/dns.yaml`

Expected results:
Expected a valid file to return

Actual results:
`<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>cloudformation/2020-04-21/dns.yaml</Key><RequestId>74634F3E16F9FED8</RequestId><HostId>+azDf7F14FlGPI0VCZ8HHuc8kl/XsvEYwqqy+wikEThIK7lbbPlMMRnqDa7dkEGbUJqCijwogM4=</HostId></Error>%`

**Comment by jimdial-aws** [comment]
Sorry you had an issue. The file is there now.
