### ISSUE TITLE
heptio-authenticator-aws was renamed to aws-iam-authenticator

### ISSUE THREAD

**Issue by satoshihirose** [awsdocs/amazon-eks-user-guide#12]
heptio-authenticator-aws using in kubectl was renamed to aws-iam-authenticator.
https://github.com/kubernetes-sigs/aws-iam-authenticator/commit/8875022195cffe6c0d37054ecd7080315ed7ff2f

The rename causes problems in the following tutorial.
https://docs.aws.amazon.com/eks/latest/userguide/configure-kubectl.html
https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html

**Comment by nrdlngr** [comment]
Thanks for raising this issue! I've updated the procedure to reflect this name change and fix the installation instructions for downloading the command with `go get`.
