### ISSUE TITLE
pod logging from fluentd to cloudwatch

### ISSUE THREAD

**Issue by farooqdevops** [awsdocs/amazon-eks-user-guide#124]
Hi

I have eks on fargate k8 cluster  and i am using fluentd as side car container to send logs to cloudwatch. My fluentd container is able to access shared volume from application container but its unable to send logs to cloudwatch. Is there some fluent-d side-car implementation which i can use as readymade template? or if there's some other better alternative for pod logging?

BR

**Comment by obrienjason** [comment]
Thanks for your question. The simplest solution might be to enable Amazon EKS control plane logging, which sends them directly to CloudWatch Logs in your account.
See this documentation for further explanation and a procedure to enable this logging:
https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html
Hope this information is helpful.
