### ISSUE TITLE
Restricting Access to Amazon EC2 Instance Profile Credentials on Windows node

### ISSUE THREAD

**Issue by ArturChe** [awsdocs/amazon-eks-user-guide#129]
Hi all,

Is there any way (script) to restrict access to Amazon EC2 instance profile credentials on Windows node? I have configured the Service Account and I want my pods to use the created IAM role. But .net app tries to get the credentials from EC2 Metadata with error:
```
[Amazon.Util.EC2InstanceMetadata:0] - Unable to contact EC2 Metadata service to obtain a metadata token. Attempting to access IMDS without a token.
```

**Comment by pgasca** [comment]
This GitHub repository is for requesting updates to documentation. For technical support requests, please refer to:
https://aws.amazon.com/premiumsupport/knowledge-center/get-aws-technical-support/
