### ISSUE TITLE
Suggest to add the notice if using amazon-k8s-node-drainer before upgrading Kubernetes 1.16

### ISSUE THREAD

**Issue by 0xlen** [awsdocs/amazon-eks-user-guide#135]
There has an issue of `amazon-k8s-node-drainer` if using Kubernetes 1.16, the Pod eviction object name should be match the Pod name.

For users already integrated the solution(e.g. using Cluster AutoScaler to do scale in), to prevent any potential issue when CA terminating the Worker Node and unable correctly send Pod eviction API, it is recommended to add notice to update/patch the `amazon-k8s-node-drainer` before upgrading the cluster version.

Reference
- https://github.com/aws-samples/amazon-k8s-node-drainer/pull/30

**Comment by obrienjason** [comment]
No longer supporting K8s 1.16.
