### ISSUE TITLE
EKS worker nodes ami local certificate expired 

### ISSUE THREAD

**Issue by rohith-vallabhaneni** [awsdocs/amazon-eks-user-guide#139]
When I make a curl request from any of the EKS worker nodes or when I'm trying to establish the secure connection over HTTPS from any of the pods running on that worker nodes, I'm receiving the following error:

<code>
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
</code>

The **EKS master version:** 1.14
**AMI ID:**  _amazon-eks-node-1.14-v20200507 | ami-0486134a23d903f10_
**AWS region:** us-west-2(Oregon)

I have also checked my domain certs, their state is **active**, the HTTPS requests are getting served from outside EKS nodes.

This is blocking me across all regions, would appreciate if it gets resolved ASAP.

Thanks in advance
-Rohith Vallabhaneni.

**Comment by rohith-vallabhaneni** [comment]
The issue is fixed, the root cause was one of the certs in my intermediate certificate chain got expired & since we have the expired one in the chain, the applications that are running  couldn't serve the requests
The intermediate certificates are ignored in the latest ca bundles and on the browser, we see this issue in the older machines and which has the old bundles, the base ami for EKS worker nodes do not have the latest bundles, which caused the whole issue.

**Comment by pgasca** [comment]
Closing based on last comment.
