### ISSUE TITLE
Latest version in referenced yaml for deployment uses image v1.6.2

### ISSUE THREAD

**Issue by TechDawg270** [awsdocs/amazon-eks-user-guide#144]
[cni-upgrades](../blob/master/doc_source/cni-upgrades.md) specifies latest recommended version as `v1.6.1`, but the
[referenced yaml](https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.6/config/v1.6/aws-k8s-cni.yaml) uses the image `v1.6.2`

**Comment by jimdial-aws** [comment]
This has been updated. Thanks for the feedback.
