### ISSUE TITLE
Make IRSA refresh token mechanics explicit

### ISSUE THREAD

**Issue by mhausenblas** [awsdocs/amazon-eks-user-guide#151]
Somewhere in the [technical overview on IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html) we should mention that the token is automatically refreshed by the kubelet, referring to the [upstream docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection):

> The kubelet will request and store the token on behalf of the pod, make the token available to the pod at a configurable file path, and refresh the token as it approaches expiration. Kubelet proactively rotates the token if it is older than 80% of its total TTL, or if the token is older than 24 hours.

**Comment by jimdial-aws** [comment]
Thanks for the feedback. I've added some text about this to the document. It will publish later today.
