### ISSUE TITLE
Fix windows support doc with GMSA support

### ISSUE THREAD

**Issue by saipenug** [awsdocs/amazon-eks-user-guide#155]
As per EKS Kubernetes version 1.16 [1] , GMSA is supported [2] feature (graduated to beta).

```
Windows GMSA support has graduated from alpha to beta, and is now supported by Amazon EKS. For more information, see Configure GMSA for Windows Pods and containers in the Kubernetes documentation.
```

However, windows-support.html [1] doc still references that GMSA is not yet supported by EKS.

```
Group Managed Service Accounts (GMSA) for Windows pods and containers is a Kubernetes 1.14 alpha feature that is not supported by Amazon EKS. You can follow the instructions in the Kubernetes documentation to enable and test this alpha feature on your clusters.
```

References:
---
[1] https://kubernetes.io/docs/tasks/configure-pod-container/configure-gmsa/
[2] https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html
[3] https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html

**Comment by jimdial-aws** [comment]
Thanks for bringing this to our attention. I've updated the document. It will publish later today.
