### ISSUE TITLE
Update apiVersion for Kubernetes 1.16

### ISSUE THREAD

**Issue by zgovani** [awsdocs/amazon-eks-user-guide#157]
The vpc-resource-controller.yaml linked in this Windows Support doc uses a deployment with:
```
apiVersion: apps/v1beta1 
```
This was deprecated in kubernetes 1.16:
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

When trying to apply to the cluster:
```
error: unable to recognize "https://amazon-eks.s3.us-west-2.amazonaws.com/manifests/us-east-1/vpc-resource-controller/latest/vpc-resource-controller.yaml": no matches for kind "Deployment" in version "apps/v1beta1"
```

Should be an easy change in just updating the apiVersion in the file

**Comment by jimdial-aws** [comment]
Thanks for the feedback. The API version for the deployment in the manifest has been updated to apps/v1 now.
