### ISSUE TITLE
EFS CSI driver image amazon/aws-efs-csi-driver:v0.3.0 broken for TLS mount options

### ISSUE THREAD

**Issue by saipenug** [awsdocs/amazon-eks-user-guide#159]
As per [#152](https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/152) GitHub issue, Docker image amazon/aws-efs-csi-driver:v0.3.0 does not support TLS mount options as `openssl` binary doesn't exist in it.

Opening this issue to add a `Note` point in the docs that, TLS is not supported for `v0.3.0` tag.

Instead `amazon/aws-efs-csi-driver:latest` image should be used to support TLS.

**Comment by jimdial-aws** [comment]
Thanks for the feedback. I've added a note to the doc about the lack of TLS mount support with the 0,3.0 version. It will publish later today.
