### ISSUE TITLE
heptio-authenticator-aws has been renamed to aws-iam-authenticator

### ISSUE THREAD

**Issue by ozbillwang** [awsdocs/amazon-eks-user-guide#16]
Seems we need update the document to replace `heptio-authenticator-aws`  to `aws-iam-authenticator`

Below is the commit in upstream 

>Renamed heptio-authenticator-aws -> aws-iam-authenticator

https://github.com/kubernetes-sigs/aws-iam-authenticator/commit/678cdff0f43d3ae4a1d9d68a5347042f14a168a8

**Comment by nrdlngr** [comment]
Thanks, we've updated the documentation to refer to the new name for the aws-iam-authenticator.
