### ISSUE TITLE
Requesting update of docs to support Cuda 10.1 and 10.2

### ISSUE THREAD

**Issue by josegonzalez** [awsdocs/amazon-eks-user-guide#163]
It would be great to have access to a more modern Nvidia Drivers in order to run more modern cuda workloads. Many libraries in the python world now default to 10.1 or 10.2. GKE supports up to 10.1 with the Nvidia 418.67 driver, so it would be great to at least be equal to their offering.

**Comment by jimdial-aws** [comment]
Thanks for the feedback. I'm closing this issue against the docs because this is feature request. I recommend that you open an issue in the [containers roadmap repo](https://github.com/aws/containers-roadmap/blob/master/CONTRIBUTING.md), where feature requests are tracked.
