### ISSUE TITLE
How to mount the pod's data into AWS s3 bucket?

### ISSUE THREAD

**Issue by jyoti-26** [awsdocs/amazon-eks-user-guide#18]

**Comment by nrdlngr** [comment]
It sounds like you are trying to push objects from your container to an S3 bucket. Do I have that correct? If so, you can use one of the AWS SDKs (or the AWS CLI) in your containerized application to push the objects to your S3 bucket.

**Comment by nrdlngr** [comment]
You can create an IAM policy that allows write permissions to your S3 bucket and apply it to your worker node instance role. However, this allows any pod or process that is running on your worker nodes to write to the bucket.

There isn't currently a more granular pod identity solution that is recommended by AWS. There are community options like KIAM and Kube2IAM that are commonly used, but it is up to you to research the security profile and decide if they are suitable solutions. AWS is currently working on a recommended solution to this problem with SIG AWS.
