### ISSUE TITLE
Cluster Autoscaler Node group IAM policy

### ISSUE THREAD

**Issue by rafaelpereyra** [awsdocs/amazon-eks-user-guide#181]
Best practices for EKS cluster is to leverage the use of IRSA. The proposed approach in the documentation is to add the policy to the Instance role 

> you must create an IAM policy with the following document and attach it to your node IAM roles.

In the knowledge center post it also replicates this but there is a note at the end of the policy warning about the risk of attaching the policy directly into the node.

https://aws.amazon.com/premiumsupport/knowledge-center/eks-cluster-autoscaler-setup/

Maybe we can add a similar warning while modifying the documentation to align with proper security guidelines?

This is the warning in the Autoscaler github repository documentation
https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/aws

>Cluster Autoscaler requires the ability to examine and modify EC2 Auto Scaling Groups. We recommend using IAM roles for Service Accounts to associate the Service Account that the Cluster Autoscaler Deployment runs as with an IAM role that is able to perform these functions. If you are unable to use IAM Roles for Service Accounts, you may associate an IAM service role with the EC2 instance on which the Cluster Autoscaler pod runs.

**Comment by jimdial-aws** [comment]
I've updated the document to use IAM roles for service accounts.
