### ISSUE TITLE
Is the cluster-endpoint page up to date for private API name resolution?

### ISSUE THREAD

**Issue by amalagaura** [awsdocs/amazon-eks-user-guide#189]
The cluster endpoint page: https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html describes integrating with AWS name servers when using private access to the EKS API Endpoint. In Dec 2019 there appears to have been a change so that the API endpoint is resolvable via public DNS (to the private IP address).

Is this public DNS resolution of the API endpoint reflected in the documentation? Because the documentation suggests we must enable the DHCP option sets for private API access and also allow the association to a route 53 private hosted zone. Is all this still accurate?

**Comment by obrienjason** [comment]
Yes, it is accurate.
