### ISSUE TITLE
Kubectl Broken Link

### ISSUE THREAD

**Issue by tutugreen** [awsdocs/amazon-eks-user-guide#190]
Get:

<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>1.17.9/2020-07-08/bin/linux/amd64/kubectl</Key>

Using: https://amazon-eks.s3.us-west-2.amazonaws.com/1.17.9/2020-07-08/bin/linux/amd64/kubectl

also other links with "2020-07-08"

In: https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/getting-started-eksctl.md

**Comment by ankon** [comment]
Given that the keys look fairly predictable, I did a bit of a "search", and it seems that the correct data is 2020-07-17, for which the kubectl (and aws-iam-authenticator on a close-by page!) do work.

**Comment by ankon** [comment]
@jimdial-aws as per https://github.com/awsdocs/amazon-eks-user-guide/pull/192#issuecomment-676736104, I guess you can close this issue as well then.
