### ISSUE TITLE
cni-upgrades.md referenced a wrong link for the manifest file

### ISSUE THREAD

**Issue by hinling-sonder** [awsdocs/amazon-eks-user-guide#211]
When I tried using https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/v.1.7.2/config/v1.7/aws-k8s-cni.yaml to download the 1.7 cni chart, I got a 404:

```
➜  k8s_upgrade curl https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/v.1.7.2/config/v1.7/aws-k8s-cni.yaml                                                                                       
404: Not Found%
```

I tried `https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.7/config/v1.7/aws-k8s-cni.yaml` and works but it gives me 1.7.5 image.

**Comment by jimdial-aws** [comment]
The document now references a URL with 1.7.5, so I think this has been resolved.
