### ISSUE TITLE
CoreDNS version mismatch for 1.18

### ISSUE THREAD

**Issue by ctrahey** [awsdocs/amazon-eks-user-guide#212]
[This doc](https://docs.aws.amazon.com/eks/latest/userguide/coredns.html) tells users to use [this coredns yaml](https://amazon-eks.s3.us-west-2.amazonaws.com/cloudformation/2020-08-12/dns.yaml), which specifies image `coredns:v1.6.6-eksbuild.1`, which is correct for 1.17 but not 1.18.

Additionally, when the correct image is used, there is an error in the coredns ConfigMap, in the Corefile, where it lists `upstream` as an option under `kubernetes cluster.local in-addr.arpa ip6.arpa {` section. This was removed in 1.7.x and causes errors.

It is possible that customer following this documentation for 1.18 will encounter DNS outages. Work around by updating image version and removing upstream from the Corefile.

**Comment by ueokande** [comment]
I propose:
1) the URL includes an EKS version instead of the release date (e.g. `https://amazon-eks.s3.us-west-2.amazonaws.com/cloudformation/1.18eks1/dns.yaml`)
2) upgrade guide uses manifest via URL, which is the same way as install guide,  instead of using `kubectl edit` or `kubectl patch`.

**Comment by jimdial-aws** [comment]
The document now points to a later version of this file. I think this issue is resolve in the new file, but feel free to re-open this issue if it's not.
