### ISSUE TITLE
GPU AMI doesn't work with CUDA 10 image

### ISSUE THREAD

**Issue by gerardo** [awsdocs/amazon-eks-user-guide#22]
The [currently documented method](https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/gpu-ami.md#example-gpu-manifest) to test GPU workers are configured properly points to the `latest` CUDA image, which is version 10. It seems the current GPU AMI doesn't support this particular version. When I run the example pod manifest, I get the following error:

```bash
container_linux.go:262: starting container process caused "process_linux.go:345: container init 
caused \"process_linux.go:328: running prestart hook 0 caused \\\"error running hook: exit status 1,
 stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --
ldconfig=@/sbin/ldconfig --device=GPU-ffa9ca4e-a464-f033-f4e9-4712c549302b --compute -
utility --require=cuda>=10.0 brand=tesla,driver>=384,driver<385 --pid=7659
 /var/lib/docker/overlay2/0e8ac16367d1fdbaef77a014319383fe142129534864f51ac90c
bded3be6bd6c/merged]\\\\nnvidia-container-cli: requirement error: invalid expression\\\\n\\\"\""
``` 

Changing the `image` version in the manifest to `nvidia/cuda:9.2-devel` works as expected. This means that the GPU AMI only supports CUDA image versions <10.0.

**Comment by nrdlngr** [comment]
Thanks for your feedback! I've updated the Cuda image to use the tag you've suggested.
