### ISSUE TITLE
Wrong Kubernetes Version

### ISSUE THREAD

**Issue by t0rr3sp3dr0** [awsdocs/amazon-eks-user-guide#227]
The table on the documentation for Platform Versions on Kubernetes 1.14 specifies Kubernetes 1.15 versions instead of 1.14 itself.

https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/platform-versions.md#kubernetes-version-114

**Comment by jimdial-aws** [comment]
1.14 is no longer supported and has been removed from this page. Sorry for the delay, but thanks for letting us know.
