### ISSUE TITLE
[load-balancing.md] Deploying AWS load balancer controller: Wrong URL for deploying TargetGroupBinding

### ISSUE THREAD

**Issue by bklein1** [awsdocs/amazon-eks-user-guide#231]
In the description on how to deploy the AWS load balancer controller to an Amazon EKS cluster, step number 6 mentions in its first section to `Install the TargetGroupBinding custom resource definitions`. There it is mentioned following command:

`kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"`

The URL github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master leads to the Github 404 page and needs to be replaced by: `https://raw.githubusercontent.com/aws/eks-charts/master/stable/aws-load-balancer-controller/crds/crds.yaml`

So the command should look like:

`kubectl apply -k "https://raw.githubusercontent.com/aws/eks-charts/master/stable/aws-load-balancer-controller/crds/crds.yaml"`

**Comment by jimdial-aws** [comment]
The documented command worked fine for me. I do receive a 404 if I try to go to the URL in a browser, but not when using it with the documented command. Feel free to re-open the issue if you're getting a 404 when using the command. Thanks.
