### ISSUE TITLE
CoreDNS: Use the ready plugin for readiness probe

### ISSUE THREAD

**Issue by dulltz** [awsdocs/amazon-eks-user-guide#241]
CoreDNS provides the [`ready`](https://coredns.io/plugins/ready/) plugin for readiness check.  It is suitable for readiness probe of CoreDNS Deployment.

However, EKS uses the [`health`](https://coredns.io/plugins/health/) plugin for readiness probe.
I think the `ready` plugin is preferable in this case.

- https://github.com/awsdocs/amazon-eks-user-guide/blob/d3cdc443573e1ac56359b616d8a9a0efb4a666e1/doc_source/coredns.md
- https://amazon-eks.s3.us-west-2.amazonaws.com/cloudformation/2020-10-29/dns.yaml

The following is an official example of using the `ready` plugin for readiness probe.
- https://github.com/coredns/deployment/blob/f22b7a37ac754da0f56e445126b8b888e0d5b567/kubernetes/coredns.yaml.sed#L54
- https://github.com/coredns/deployment/blob/f22b7a37ac754da0f56e445126b8b888e0d5b567/kubernetes/coredns.yaml.sed#L152-L156

**Comment by jimdial-aws** [comment]
Closing due to it not being a documentation issue. A similar issue exists in the [Containers Roadmap](https://github.com/aws/containers-roadmap/issues/941) which is where this needs to be addressed. Progress on the issue can be tracked there.
