### ISSUE TITLE
EKS v1.16 platform version mismatch

### ISSUE THREAD

**Issue by rohith-vallabhaneni** [awsdocs/amazon-eks-user-guide#243]
![platform_version_eks 4](https://user-images.githubusercontent.com/26318323/98646363-46b10580-2359-11eb-8729-0aa60497fce0.png)
Hi there,
I'm upgrading my EKS cluster to v1.16 from v1.15 in the **N.Virginia** region. After the upgrade, my cluster behaves in an odd way on debugging I see the platform version is set to **_eks.4_** which comes with the master version - v1.16.15 but the latest worker node AMI to still pointing to v1.16.13 which is compatible with **eks.3**
FYI:
https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#Images:visibility=public-images;search=amazon-eks-node-1.16-v;sort=desc:creationDate 

I don't have control over choosing the platform version from my terraform templates: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#platform_version

I don't see any reference for the new platform version **(eks.4)** in any of the AWS docs or the Github release notes
FYI:
https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/platform-versions.md#kubernetes-version-116 

https://docs.aws.amazon.com/eks/latest/userguide/platform-versions.html 

**ISSUES:**

- Not all worker nodes joining the cluster

- On restart of any pod, new pods are not showing up

- I don't see any _/etc/cni_ folder in the worker nodes that are not getting attached

- On removing all worker nodes and creating new ones, again few are adding and few are not on the same subnet

I feel the new ami for **eks.4** platform version that is compatible with k8s v1.16.15 should solve the issues.

**NOTE:**

- I only see the new platform version update in the N.Virginia region(us-east-1), I have made a similar update in Oregon(us-west-2) region and the update is working fine without any issues and I don't see the new platform version(eks.4) in Oregon region.

Any help in fixing it will be appreciated, I cannot downgrade to 1.15 nor upgrade to 1.17 to fix it.
Thanks

**Comment by jimdial-aws** [comment]
Sorry for the delayed response. I assume your problem is already resolved. In [Amazon EKS platform versions](https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/platform-versions.md) it says "Amazon EKS might publish a new node AMI with a corresponding patch version. However, all patch versions are compatible between the EKS control plane and node AMIs for a given Kubernetes minor version." Given that, I'm not sure why you had problems, but my apologies if you did.
