### ISSUE TITLE
Broken link to Kubernetes Dashboard deployment yaml file

### ISSUE THREAD

**Issue by RothAndrew** [awsdocs/amazon-eks-user-guide#26]
Re: [this page](https://docs.aws.amazon.com/eks/latest/userguide/dashboard-tutorial.html#view-dashboard)

This link now returns a 404: `kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml`

The kubernetes/dashboard repo now recommends using this command:

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended/kubernetes-dashboard.yaml
```

**Comment by nrdlngr** [comment]
Thanks for bringing this to our attention. We've opted to use the latest release branch for the dashboard instead of master. The dashboard has been updated accordingly, and I've tested that it works on both 1.10 and 1.11 clusters.
