### ISSUE TITLE
Failed to validate if SLR: AWSServiceRoleForAmazonEKSForFargate already exists due to missing permissions for 'iam:GetRole'

### ISSUE THREAD

**Issue by bestwade22** [awsdocs/amazon-eks-user-guide#279]
Failed to validate if SLR: AWSServiceRoleForAmazonEKSForFargate already exists due to missing permissions for 'iam:GetRole'

receive this on creating fargate profile, did anyone know wt is the aws_service_name for SLR: AWSServiceRoleForAmazonEKSForFargate?

**Comment by pgasca** [comment]
This GitHub repository is for requesting updates to documentation. For technical support requests, see:
https://aws.amazon.com/premiumsupport/knowledge-center/get-aws-technical-support/
