### ISSUE TITLE
Ruby 2.x does not support IRSA

### ISSUE THREAD

**Issue by bruecktech** [awsdocs/amazon-eks-user-guide#281]
Hello

the [documentation](https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/iam-roles-for-service-accounts-minimum-sdk.md) states that AWS SDK for Ruby 2.11.345 is the minimum required version to support IAM roles for Service Accounts. This is not true. The minimum version is 3.58.0 as stated in the [CHANGELOG](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/CHANGELOG.md#3580-2019-07-01).

Regards
Johannes

**Comment by jimdial-aws** [comment]
I've updated the document to reflect this change. It will publish later today. Thanks for letting us know and for using Amazon EKS.
