### ISSUE TITLE
EFS csi driver link is broken

### ISSUE THREAD

**Issue by timothyaws** [awsdocs/amazon-eks-user-guide#283]
Link to AWS efs-csi-driver is broken on https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html

When running provided command
kubectl apply -k "github.com/kubernetes-sigs/aws-efs-csi-driver/tree/release-1.0/deploy/kubernetes/overlays/stable/ecr"

Will error out with 
error: evalsymlink failure on '/tmp/kustomize-582842524/tree/release-1.0/deploy/kubernetes/overlays/stable/ecr' : lstat /tmp/kustomize-582842524/tree: no such file or directory

Workaround:

Run kubectl apply -k "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/ecr/?ref=release-1.0"

**Comment by adrian-hincu** [comment]
@timothyaws any ideas when the fix will be merged?
Thanks!

**Comment by timothyaws** [comment]
@adrian-hincu this has been fixed in #284

**Comment by adrian-hincu** [comment]
Thank you! :)
