### ISSUE TITLE
Question about eks nodegroup update behaviour

### ISSUE THREAD

**Issue by dza89** [awsdocs/amazon-eks-user-guide#290]
https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/managed-node-update-behavior.md

Step 5 says:

```Amazon EKS randomly selects a node in the node group and evicts all pods from it.```

Does that mean it could also evict a new spun up node? Or it randomly selects a node found in step 4?
It's not really clear to me

**Comment by pgasca** [comment]
We did a complete rewrite of this section with more details.
