### ISSUE TITLE
“Getting started with the console and AWS CLI” does not work for releases prior to 1.18

### ISSUE THREAD

**Issue by herrwieger** [awsdocs/amazon-eks-user-guide#323]
Trying to follow the current guide “Getting started with the console and AWS CLI" gives an error for eks releases prior to 1.18. This happens when trying to associate the Kubernetes service account used by the VPC CNI plugin to the IAM role.
Before 1.18 the AmazonEKS_CNI_Policy needed to be associated to the  Amazon EKS worker node role.
Would be great if you could support the current and all relevant prior eks versions with the appropriate documentation.

**Comment by MMichael-S** [comment]
Same issue to me. :(

When I run the CLI command in the guide

aws eks update-addon \
  --cluster-name EKS_CLUSTER_NAME \
  --addon-name vpc-cni \
  --service-account-role-arn arn:aws:iam::xxxxx:role/EKS-TEST-EKSCNIRole \
  --region ap-southeast-1 

I got the error msg as following:
An error occurred (ResourceNotFoundException) when calling the UpdateAddon operation: No addon: vpc-cni found in cluster: EKS-CLUSTER_NAME.

The error will cause that I can't create managed nodegroup, error msg show in the EKS console

Ready | False | runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized

How can I fix it? Thank you very much.

**Comment by MMichael-S** [comment]
Workaround:
Refer to the following document link and after executing the following command, Pod aws-node status return to normal.

https://docs.aws.amazon.com/eks/latest/userguide/cni-iam-role.html

kubectl annotate serviceaccount \
  -n kube-system aws-node \
  eks.amazonaws.com/role-arn=arn:aws:iam::<AWS_ACCOUNT_ID>:role/<AmazonEKSCNIRole>

kubectl delete pods -n kube-system -l k8s-app=aws-node


I suggest adding a special note where appropriate in the document "Getting started with the console and AWS CLI".

**Comment by jimdial-aws** [comment]
I'm sorry to hear you ran into an issue. The important note at the top of the page says that you should use the Create Cluster and Amazon EKS nodes guides if you want to create a cluster with values other than the defaults used in the Getting started guide. The current Kubernetes default is 1.18, so the instructions should work for you. It sounds like you need to use non-default options, so you'll want to use the Create cluster and Amazon EKS nodes guides, which address other options.

Thanks for using Amazon EKS.

**Comment by MMichael-S** [comment]
> I'm sorry to hear you ran into an issue. The important note at the top of the page says that you should use the Create Cluster and Amazon EKS nodes guides if you want to create a cluster with values other than the defaults used in the Getting started guide. The current Kubernetes default is 1.18, so the instructions should work for you. It sounds like you need to use non-default options, so you'll want to use the Create cluster and Amazon EKS nodes guides, which address other options.
> 
> Thanks for using Amazon EKS.

Thank you for your clarification.
