### ISSUE TITLE
Do you recommend downgrading KubeProxy?

### ISSUE THREAD

**Issue by maur1th** [awsdocs/amazon-eks-user-guide#326]
@jimdial-aws 3 weeks ago you pushed a commit https://github.com/awsdocs/amazon-eks-user-guide/commit/3c8526dec48ed1de498449d7c5c3398c01911fe1 which resulted in recommending downgrading KubeProxy to a previous version. Was it intended? If so, is it possible to know why?

For context, we parse [the resulting page](https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html) everyday to ensure we're running the recommended versions on our clusters.

**Comment by jimdial-aws** [comment]
The version was changed to match what is currently deployed with new clusters. It was brought to our attention that the previous documented version did not match what is currently deploy with new clusters, so the change corrected that. My apologies for any inconvenience this error may have caused.
