### ISSUE TITLE
EBS CSI document has hardcoded the region

### ISSUE THREAD

**Issue by Kadan7** [awsdocs/amazon-eks-user-guide#343]
https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html

{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::<AWS_ACCOUNT_ID>:oidc-provider/**_**oidc.eks.us-west-2.amazonaws.com**_**/id/<XXXXXXXXXX45D83924220DC4815XXXXX>"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "**_oidc.eks.us-west-2.amazonaws.com_**/id/<XXXXXXXXXX45D83924220DC4815XXXXX>:sub": "system:serviceaccount:kube-system:ebs-csi-controller-sa"
        }
      }
    }
  ]
}

**Comment by pgasca** [comment]
I've replaced the hardcoded regions with placeholders and instructions to replace the placeholders.
