### ISSUE TITLE
Add note in Launch template support page

### ISSUE THREAD

**Issue by nameprabhat** [awsdocs/amazon-eks-user-guide#348]
Hello,

Regarding launch template support 
https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/launch-templates.md

Please add below note in launch template page stating:

"EKS creates a new launch template by copying the launch template provided by user and use it with the autoscaling group of nodegroup"

This would clarify that launch template supplied by user and attached to ASG are different. And it will make the launch template support process more clear. Thanks,

**Comment by pgasca** [comment]
I incorporated that detail. I also rewrote the first paragraph of the section for greater clarity and less redundancy. The public website have the update later this week.
