### ISSUE TITLE
Link does work

### ISSUE THREAD

**Issue by sanstorage4u** [awsdocs/amazon-eks-user-guide#35]
http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/login 

but below will work 

http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/#!/overview?namespace=default

**Comment by nrdlngr** [comment]
Sorry for the delayed response. I tested this procedure today and the link you posted from the documentation works fine for me.

I'm closing this issue.
