### ISSUE TITLE
Ambiguity in instructions for using existing security group in ENIConfig

### ISSUE THREAD

**Issue by vissree** [awsdocs/amazon-eks-user-guide#350]
From https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html

Step 6: ENIConfig created with a custom security group

Step 8: Instead of switching to node group security group, if one want to continue with the same security group that was used in Step 6, the security group must meet the minimum or required settings discussed here https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html or the pods in these worker nodes will not be able to reach control plane endpoints.

Adding a note here linking to the Security group requirements will make this clear.

**Comment by jimdial-aws** [comment]
This document has likely changed quite a bit since you filed this issue. I've added another bullet to the note in step 5a to address this though.
