### ISSUE TITLE
ICE Error explanation

### ISSUE THREAD

**Issue by badaldavda8** [awsdocs/amazon-eks-user-guide#36]
Can this be explained further by providing an example or by explaining it in detail -

"Retry creating your cluster with subnets in your cluster VPC that are hosted in the Availability Zones returned by this error message."

Also, is this related to unavailability of EC2 instances in the AZ or is this because of unavailability of EKS Cluster altogether in the AZ?

And what about UnsupportedAvailabilityZoneException? Can this be explained a little bit more?

If the zone is not supported, will it ever be supported or is it in the process of being supported?

**Comment by nrdlngr** [comment]
From our [troubleshooting guide](https://docs.aws.amazon.com/eks/latest/userguide/troubleshooting.html):

If you receive the following error while attempting to create an Amazon EKS cluster, then one of the Availability Zones you specified does not have sufficient capacity to support a cluster.

```
Cannot create cluster 'example-cluster' because us-east-1d, the targeted availability zone, does not currently have sufficient capacity to support the cluster. Retry and choose from these availability zones: us-east-1a, us-east-1b, us-east-1c
```

Retry creating your cluster with subnets in your cluster VPC that are hosted in the Availability Zones returned by this error message.

So in this example, you would create your cluster with subnets from us-east-1a, us-east-1b, and/or us-east-1c. Does this explanation solve your issue?

**Comment by badaldavda8** [comment]
Yes :) Thanks a lot!
