### ISSUE TITLE
eks-optimized-ami.md looks to be referencing to the wrong AMI's

### ISSUE THREAD

**Issue by psantora-amazon** [awsdocs/amazon-eks-user-guide#366]
https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/eks-optimized-ami.md

Documentation here https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html for US West (Oregon) (us-west-2) 1.20.4 and 1.19.6 show the same AMI ID for 1.20 (ami-05674d6c91201b508) for folks who want to upgrade potentially. Is this correct or do we normally have different AMI's per version? Is the 1.19.6 link wrong?

Looks like
- 1.20.4 goes to 1.20
- 1.19.6 goes to 1.20
- 1.18.19 goes to 1.19
- 1.17.12 goes to 1.18

Can someone help verify this? If this is incorrect, then it's misleading to customers and must be rectified ASAP.

**Comment by rtripat** [comment]
We are looking into this

**Comment by visunali** [comment]
Fix is live now. We have corrected the doc. Thank you for pointing this out.
