### ISSUE TITLE
Please mention/point to the aws-eks-ami release in the AMI list

### ISSUE THREAD

**Issue by ankon** [awsdocs/amazon-eks-user-guide#37]
It's extremely difficult right now to figure out what has changed in the AMIs: https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html only has region specific AMI IDs, the commit logs tend to be in the shape of "update AMI ids", the market place doesn't have a changelog -- but it does point to version numbers.

What I right now do is to look at the history of the eks-optimized-ami.html, try to find back the ID I used last, and then walk through the history, assuming that each of the changes correlates to an entry in the [amazon-eks-ami changelog](https://github.com/awslabs/amazon-eks-ami/blob/master/CHANGELOG.md).

I then take the current value of the AMI ID for my region, and update my internal documentation to point to that AMI ID. Every few weeks I check again with the same process, and update my docs again (and potentially even replace nodes).

**Comment by tabern** [comment]
@ankon today we've added Kubernetes patch version numbers to the AMI lists. Hopefully this helps a bit with identifying when a new AMI ships (typically for new minor and patch version releases).

https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html

**Comment by ankon** [comment]
Thanks for that.

However, that still doesn't really change the process in finding what exactly has changed in the AMIs.

I thought a bit about what would help me, and basically it is really just a change in the wording so that the eks-optimized-ami.html not just mentions the produced AMI IDs, but also the name of the tag/changelog entry in the amazon-eks-ami changelog. I would then be able to take that value, and in my own documentation write down which version we deploy, and which AMI ID was used. I'm already watching for new releases in amazon-eks-ami.

**Comment by nrdlngr** [comment]
Hi @ankon. The tags in the changelog correspond to the names of the AMIs. So you can describe any AMI that we have published publicly and get the name of the AMI, compare it to its name in the changelog, and then see the differences for that revision. Here is an AWS CLI command to describe today's recommended 1.13 worker node AMI:
```
aws ec2 describe-images --region us-west-2 --image-ids ami-089d3b6350c1769a6 --query Images[].Name
[
    "amazon-eks-node-1.13-v20190614"
]
```
So you could run this command on your current worker node AMI, and on the latest worker node AMI, and then you could infer which changelog entries separate the two. Does this workaround resolve your issue?

**Comment by ankon** [comment]
@nrdlngr that looks promising indeed, at least it makes the annoying "find the matching thing" step be quick and painless. Thanks!

**Comment by nrdlngr** [comment]
Great! I'll close this issue then.
