### ISSUE TITLE
v1.18.9-20210322 wrong NVIDIA driver version for Amazon EKS optimized accelerated Amazon Linux AMI 

### ISSUE THREAD

**Issue by damerakd** [awsdocs/amazon-eks-user-guide#383]
The document states that for AMI Version: 1.18.9-20210322, NVIDIA driver version is 460.27.04. However when i launch a AMI in us-east-1 region ami-00a430391abee258d, noticed that driver version is 460.32.03.

find /usr/lib/modules -name nvidia.ko -exec modinfo {} \;
filename:       /usr/lib/modules/4.14.225-168.357.amzn2.x86_64/extra/nvidia.ko
alias:          char-major-195-*
version:        460.32.03
supported:      external
license:        NVIDIA
srcversion:     9BFA7969070552C6938D8A8
alias:          pci:v000010DEd*sv*sd*bc03sc02i00*
alias:          pci:v000010DEd*sv*sd*bc03sc00i00*
depends:        i2c-core
retpoline:      Y
name:           nvidia
vermagic:       4.14.225-168.357.amzn2.x86_64 SMP mod_unload modversions

Please update the docs to reflect the change. Currently making use of 1.18.9-20210310 AMI version (ami-089f9a2a14c92f7e3) which contains 460.27.04 NVIDIA driver version.

**Comment by pgasca** [comment]
Confirmed here:
https://github.com/awslabs/amazon-eks-ami/blob/master/CHANGELOG.md#ami-release-v20210322

Updated source, public website will be updated later this week.
