### ISSUE TITLE
Recent commit adds China specific instructions to docs.aws.amazon.com

### ISSUE THREAD

**Issue by bloopletech** [awsdocs/amazon-eks-user-guide#405]
Just now I was looking up some Fargate on EKS documentation, and ended up on https://docs.aws.amazon.com/eks/latest/userguide/metrics-server.html .

At a minimum, this page has an issue: It instructs the user to take actions that are only relevant when using AWS in China, without any directions or context that these instructions are not required and won't work outside AWS in China.

The larger issue is that, as far as I know, docs.aws.amazon.com doesn't usually include any China-specific information.

Looking in this repo I found that this change to this page was made in this commit: https://github.com/awsdocs/amazon-eks-user-guide/commit/fb9f4c5c17f247a830a1c47776b83db8e211a620

This commit seems to not just add China-specific information in a few places, but also does this by removing globally relevant information and replace it with China-specific information.

Also, this commit was made directly to the master branch without any PR being raised, or any public review process being followed; I'm not sure if that is in line with this repo's governance model or not.

**Comment by obrienjason** [comment]
This content is now appropriate for the region.
