### ISSUE TITLE
Are k8s secrets re-encrypted when using AssociateEncryptionConfig API?

### ISSUE THREAD

**Issue by froblesmartin** [awsdocs/amazon-eks-user-guide#406]
Hello! :smile: 

As said at the bottom of: https://github.com/awsdocs/amazon-eks-user-guide/blob/31854ca0050a35be37537bd0fe1422a750fab291/doc_source/update-cluster.md

> Note
> eksctl users do not need to run the following command unless they chose to opt-out of re-encrypting their secrets automatically.

I have performed the update to EKS using the Terraform AWS EKS module, that uses the Terraform AWS provider, which uses the Go SDK (https://docs.aws.amazon.com/sdk-for-go/api/service/eks/#EKS.AssociateEncryptionConfig). It is not said anywhere, but the update has taken 52 mins for my cluster, and I think it did re-encrypt all existing secrets automatically during the EKS update as I see in CloudTrail a lot of interactions with KMS from EKS. 

If this the case, could it be specified in which specific cases is the post manual re-encryption needed?

Thank you in advance!

**Comment by obrienjason** [comment]
In the console, there is no option to opt out of re-encrypting secrets, so this command is only necessary for eksctl.

**Comment by froblesmartin** [comment]
Hi @obrienjason ! Thanks for your reply! :)

But the documentation says: 

> After you have enabled encryption on your cluster, you will need to encrypt all existing secrets with the new key:
> Note
> eksctl users do not need to run the following command unless they chose to opt-out of re-encrypting their secrets automatically.
> 
> `kubectl get secrets --all-namespaces -o json | kubectl annotate --overwrite -f - kms-encryption-timestamp="<time value>"`

What I understand from that statement is that, in order to get the secrets encrypted with the new key, you need to execute that command to add the annotation in all secrets.

But what I think is that, after enabling encryption, that command is not needed to be executed because all secrets get automatically encrypted. I am not talking about opting out. So, the question is if that command is really necessary in any case?
