### ISSUE TITLE
no mention of --balancing-ignore-label

### ISSUE THREAD

**Issue by nbrational** [awsdocs/amazon-eks-user-guide#411]
This relates to issue [kubernetes/autoscaler#3515](https://github.com/kubernetes/autoscaler/issues/3515)

When using `--balance-similar-node-groups=true` to balance scaling across multiple node groups, each in a different AZ, scaling across node group ASGs is not uniform unless all node labels match. 

I created 3 node groups using eksctl (each in a different AZ) and found that a node label `eks.amazonaws.com/sourceLaunchTemplateId` (and possibly `eks.amazonaws.com/sourceLaunchTemplateVersion`) is different across nodes of different node groups. Scaling was not uniform unless I passed `--balancing-ignore-label=eks.amazonaws.com/sourceLaunchTemplateId`. This labels is not covered in the list of [aws ignored labels](https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-1.19.0/cluster-autoscaler/processors/nodegroupset/aws_nodegroups.go) or [BasicIgnoredLabels](https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-1.19.0/cluster-autoscaler/processors/nodegroupset/compare_nodegroups.go). 

Think it will be useful to include a note in documentation so that user can compare the node labels and pass `--balancing-ignore-label` for each label that needs ignoring.

**Comment by stevehipwell** [comment]
You'll also need https://github.com/kubernetes/autoscaler/issues/3673 to be fixed and the chart to be released (CA chart releases are a manual process after the PR has been merged and the chart has been built).

**Comment by stevehipwell** [comment]
I've opened https://github.com/kubernetes/autoscaler/issues/4228 to request better defaults and documentation around the ignore labels.

**Comment by pgasca** [comment]
I've handled incorporating this information as part of incorporating content for PR. I'm waiting on an engineer to do full confirmation on my summary. But feel free to re-open if there's a need beyond what will be covered with PR: "When setting `--balance-similar-node-groups` to true, make sure that the node groups you want the Cluster Autoscaler to balance have matching labels (except for automatically added zone labels). You can pass a `--balancing-ignore-label` flag to nodes with different labels to balance them regardless, but this should only be done as needed."
