### ISSUE TITLE
can the region/ecr-repo map be published as json?

### ISSUE THREAD

**Issue by reschenburgIDBS** [awsdocs/amazon-eks-user-guide#418]
Hi

This table here: add-ons-images.md#amazon-eks-add-on-container-image-addresses

It would be useful to have this published as .json or something similarly parable.

I don't really fancy keeping this map up-to-date manually in my terraform code. 

Thanks!

**Comment by jimdial-aws** [comment]
It's not something I can do in the documentation. I encourage you to create an issue in the [Containers roadmap](https://github.com/aws/containers-roadmap/issues) repo with the request. If engineering publishes it, the documentation can link to it.
