### ISSUE TITLE
Controller issue : dynamic provisionning

### ISSUE THREAD

**Issue by tontondematt** [awsdocs/amazon-eks-user-guide#426]
Hello, 

I am trying to setup efs using the aws official csi driver. (I am currently using the efs provisionner and it's working just fine)
I followed the user guide to the letter as descibed in here https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html
checked, double checked and triple checked.

I am having an issue with the csi controller : 
when i try to create a PVC which points to my storage class which it self points the my efs , i am faced with this error and have no way to find what's going on as the logs don't say too much : 

`I0804 16:27:47.294125       1 controller.go:58] CreateVolume: called with args {Name:pvc-81004c2c-d6ba-42c3-86f7-44c08e47e991 CapacityRange:required_bytes:5368709120  VolumeCapabilities:[mount:<> access_mode: ] Parameters:map[csi.storage.k8s.io/pv/name:pvc-81004c2c-d6ba-42c3-86f7-44c08e47e991 csi.storage.k8s.io/pvc/name:efs-claim csi.storage.k8s.io/pvc/namespace:kube-system directoryPerms:700 fileSystemId:fs-bef87c8a gidRangeEnd:2000 gidRangeStart:1000 provisioningMode:efs-ap] Secrets:map[] VolumeContentSource: AccessibilityRequirements: XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0804 16:27:47.294289       1 cloud.go:218] Calling DescribeFileSystems with input: {
  FileSystemId: "fs-bef87c8a"
}
E0804 16:27:57.293533       1 driver.go:103] GRPC error: rpc error: code = Internal desc = Failed to fetch File System info: Describe File System failed: RequestCanceled: request context canceled
caused by: context deadline exceeded`

Reading this would suggest that my service account doesn't have the permissions to do a describe file system , but it should combining these : 
`
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::XXXXXXXXXXXXXXXXXXXX:oidc-provider/oidc.eks.eu-west-1.amazonaws.com/id/XXXXXXXXXXXXXXXXXXXXXXX"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "oidc.eks.eu-west-1.amazonaws.com/id/XXXXXXXXXXXXXXXXXXXXXXX:sub": "system:serviceaccount:kube-system:efs-csi-controller-sa"
        }
      }`

`{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "elasticfilesystem:DescribeAccessPoints",
        "elasticfilesystem:DescribeFileSystems"
      ],
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": [
        "elasticfilesystem:CreateAccessPoint"
      ],
      "Resource": "*",
      "Condition": {
        "StringLike": {
          "aws:RequestTag/efs.csi.aws.com/cluster": "true"
        }
      }
    },
    {
      "Effect": "Allow",
      "Action": "elasticfilesystem:DeleteAccessPoint",
      "Resource": "*",
      "Condition": {
        "StringEquals": {
          "aws:ResourceTag/efs.csi.aws.com/cluster": "true"
        }
      }
    }
  ]
`

My test pod is running on an eks cluster inside a vpc.
I can provide more infos if needed.

**Comment by tyler-bixal** [comment]
I can recreate this issue. I'd like to point out that it only occurs with dynamic provisioning and static provisioning can still be used. [The EFS CSI Driver project](https://github.com/kubernetes-sigs/aws-efs-csi-driver) might be a more appropriate place to report this type of issue as it seems like a bug in the driver itself.

**Comment by pgasca** [comment]
Thank you @tontondematt and @tyler-bixal , I've recreated the issue in the suggested repo:
https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/555
