### ISSUE TITLE
managed flag for eks inferentia clusters

### ISSUE THREAD

**Issue by wernerchao** [awsdocs/amazon-eks-user-guide#430]
Following this doc here: https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/inferentia-support.md

Even though the doc specifies this:
`"Amazon EC2 Inf1 instances are not currently supported with managed node groups."`
In the `eksctl create cluster` command in the doc, it is still including the `--managed` flag.

I followed along and the eks node I created did not have aws neuron runtime available, I confirmed it with the commands:
```
neuron-ls
systemctl status neuron-rtd
```
both returned no commands available.
When I deployed a docker image built on `neuron-rtd` also resulted in error.
I think perhaps should not be using the `--managed` flag and use `--node-ami ami-0ccc71d716eb5d6a4` flag instead?
Or I am missing something here?

Thanks!

**Comment by jimdial-aws** [comment]
I've updated to remove the --managed flag which is no longer needed. Inferentia is now supported for managed node groups, so that statement has also been removed. Apologies for the delayed response, but hopefully this resolves your issue. Thanks for using Amazon EKS.
