### ISSUE TITLE
Update documentation to resolve deleted Cluster Creator issue. 

### ISSUE THREAD

**Issue by arpipati** [awsdocs/amazon-eks-user-guide#440]
Many customers have reached out requesting assistance to find out how to regain access to an EKS Cluster for which the EKS cluster creator IAM user has been deleted.

The solution for this issue is to recreate the cluster creator IAM user with the exact same name as original cluster creator. 
```
Recreate the IAM user with the exact same name as before. Since IAM resource ARNs are based on names, by recreating the user with exact same name will allow you to access the EKS cluster with that user, i.e. EKS will recognize that IAM user. If you know the user details, then recreating the same user should be fairly straightforward.  
```
However, this information is not found in any public facing documentation. It would help if this information is updated in the public docs so that customers can quickly find the answer and help reduce case load for AWS support.

**Comment by obrienjason** [comment]
Added links to this scenario and a resolution.
