### ISSUE TITLE
AWS IAM authenticator curl command downloads file without .exe extension

### ISSUE THREAD

**Issue by AdityaGupta1** [awsdocs/amazon-eks-user-guide#47]
The Windows instructions at https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/install-aws-iam-authenticator.md say to run the command `curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.12.7/2019-03-27/bin/windows/amd64/aws-iam-authenticator.exe`, but the command downloads a file that I had to manually rename to `.exe` before it worked.

**Comment by CDillinger** [comment]
Is this fixed by [6cd0e8d](https://github.com/awsdocs/amazon-eks-user-guide/commit/6cd0e8d0e0c13ea1fb7c1e9eaf789dd35133f4cf#diff-874802bbf35e10381ea2d27495052891)?

**Comment by AdityaGupta1** [comment]
Yes it is.
