### ISSUE TITLE
Docs: Metric-server with insecure_skip_tls_verify=false

### ISSUE THREAD

**Issue by V3ckt0r** [awsdocs/amazon-eks-user-guide#470]
The documentation listed [here](https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/metrics-server.md), describes deploying the `metrics.k8s.io` APIService with `insecureSkipTLSVerify: true`

Could the documentation please be updated to show how this can be secured on EKS

**Comment by obrienjason** [comment]
This documentation does not list this deployment flag any longer. We will work on a broader security update for this content and release it in the future.
