### ISSUE TITLE
Highlight CoreDNS connectivity requirements in security group considerations

### ISSUE THREAD

**Issue by benmccown** [awsdocs/amazon-eks-user-guide#474]
In the [documentation for security group considerations](https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/sec-group-reqs.md) there are node group security requirements documented.

One core requirement within any regular EKS Cluster is that tcp and udp port 53 be opened from all pods (source of all node security groups) to CoreDNS pods (inbound rule on nodes running CoreDNS pods) for name resolution to work within the cluster.

We see this covered in the existing documenation with the below rule.

|  | Protocol | Port range | Source | Destination | 
| --- | --- | --- | --- | --- | 
| Minimum inbound traffic \(from other nodes\) |  Any protocol that you expect your nodes to use for inter\-node communication  |  Any ports that you expect your nodes to use for inter\-node communication  |  All node security groups  |  | 

While this does technically cover the requirement for pods to able to reach CoreDNS, I would expect that most customers new to EKS would not be aware of the specific CoreDNS requirements (tcp/udp port 53 opened inbound to CoreDNS pods) without being explicitly told about it. Someone new to Kubernetes may not be aware that "any XXX that you expect your nodes to use for internode communication" would include basic DNS connectivity, since they may expect requests to go the VPC DNS Resolver or they may expect DNS to be running within the control plane.

As such I propose this be highlighted explicitly with the addition of a new table row beneath the existing entry. Below is my proposition, but anything to this effect would do.

|  | Protocol | Port range | Source | Destination | 
| --- | --- | --- | --- | --- | 
| Minimum inbound traffic \(from other nodes\) |  Any protocol that you expect your nodes to use for inter\-node communication  |  Any ports that you expect your nodes to use for inter\-node communication  |  All node security groups  |  | 
| Minimum inbound traffic for nodes running CoreDNS pods \(from other nodes\) | TCP and UDP | 53 | All node security groups | |

**Comment by jimdial-aws** [comment]
Thanks for your submission. I've added the content. It will publish later today.
