### ISSUE TITLE
VPC CNI instructions for enabling IRSA - eksctl instructions incomplete

### ISSUE THREAD

**Issue by bkonicekprivo** [awsdocs/amazon-eks-user-guide#482]
https://docs.aws.amazon.com/eks/latest/userguide/cni-iam-role.html

The eksctl documentation claims that running 
```
eksctl create iamserviceaccount \
    --name aws-node \
    --namespace kube-system \
    --cluster cluster_name \
    --attach-policy-arn arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy \
    --approve \
    --override-existing-serviceaccounts
```
will automatically enable the OIDC provider. When I ran this on my EKS cluster using `eksctl v0.76.0` it failed because there was no OIDC identity provider. I had to first run `eksctl utils associate-iam-oidc-provider` in order to get it to work.

Additionally, the eksctl documentation does not clarify that you have to restart the `aws-node` pods in order for them to start using the new role. I had to look through the AWS Management Console steps and find where it instructs you to restart them.

**Comment by jimdial-aws** [comment]
Sorry for the inaccuracy and incompleteness. I'm glad you were able to resolve the issues. The document is updated to fix both of these issues and will publish later this week.
