### ISSUE TITLE
Problem changing launch template version

### ISSUE THREAD

**Issue by joaolgn1985** [awsdocs/amazon-eks-user-guide#484]
Hello everyone, I'm applying some changes such as sg, when I run apply, it makes the sg change, but it doesn't change the launch template version, I need to run the plan again to apply the new launch template version.

I need to support with problem.

Thanks
João Lobo

**Comment by pgasca** [comment]
This repository is for errors specific to documentation. For product support issues, please see:
https://aws.amazon.com/premiumsupport/knowledge-center/get-aws-technical-support/
