### ISSUE TITLE
m6i instance types missing from 'security-groups-for-pods' page

### ISSUE THREAD

**Issue by lesteenman** [awsdocs/amazon-eks-user-guide#488]
The m6i instance types are missing from the table listing the allowed branch network interfaces, on this page: https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html#supported-instance-types.

**Comment by jimdial-aws** [comment]
Thanks for bringing this to our attention. I've removed the list of instances from the document and instead, linked to https://github.com/aws/amazon-vpc-resource-controller-k8s/blob/master/pkg/aws/vpc/limits.go for the list of supported instances. By doing so, the document won't get out of sync with the authoritative list.
