### ISSUE TITLE
Add explanation for why --skip-nodes-with-system-pods=false is recommended

### ISSUE THREAD

**Issue by Ruyven** [awsdocs/amazon-eks-user-guide#492]
In the Cluster Autoscaler docs, section [Deploy the Cluster Autoscaler](https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/autoscaling.md#deploy-the-cluster-autoscaler), it is recommended to set `--skip-nodes-with-system-pods=false`. Can anyone shed some light on why that is the default recommendation, rather than adding Pod Disruption Budgets that allow evicting system pods in a safe manner?

An example for why this default recommendation could be a problem is that it can cause DNS resolution issues:  
https://stackoverflow.com/questions/62551303/application-dns-resolution-problem-while-nodes-are-scaling-down

**Comment by obrienjason** [comment]
These settings are to rebalance across availability zones and to enable scale to zero. I'll update the documentation to explain this, but these settings are to ensure available computing and to prevent issues with old or underutilized nodes being left in the cluster. This will be updated shortly.
