### ISSUE TITLE
Misleading instructions around OIDC setup for AWS load balancer controller

### ISSUE THREAD

**Issue by ohookins** [awsdocs/amazon-eks-user-guide#503]
Source: https://github.com/awsdocs/amazon-eks-user-guide/tree/master/doc_source/aws-load-balancer-controller.md

Specifically around step 3 of setting up, where we create the OIDC linkage between the role and the cluster. If a user is trying to automate this with IaC they will set up the roles in their tool of choice, and the instructions are misleading.

If you create a new IAM role with the instructions given, you will end up with a trust policy similar to this:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Principal": {
                "Federated": "arn:aws:iam::xxxx:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/EXAMPLE"
            },
            "Condition": {
                "StringEquals": {
                    "oidc.eks.us-east-1.amazonaws.com/id/EXAMPLE:aud": [
                        "sts.amazonaws.com"
                    ]
                }
            }
        }
    ]
}
```

You are instructed to ensure the region and OIDC provider ID are correct for your cluster (which they should be anyway if you create it in the console). Then you are instructed to change the condition notation for `aud` (audience) to `sub` (subject) and `sts.amazonaws.com` to a notation referring to the service account for the controller in the cluster.

According to https://aws.amazon.com/premiumsupport/knowledge-center/eks-load-balancer-webidentityerr/ this doesn't appear to be enough. You need a condition similar to the following:
```
"Condition": {
        "StringEquals": {
          "oidc.eks.<REGION>.amazonaws.com/id/<Your-EKS-cluster-OIDC-Provider-ID>:sub": "system:serviceaccount:kube-system:<aws-load-balancer-controller-serviceaccount>",
          "oidc.eks.<REGION>.amazonaws.com/id/<Your-EKS-cluster-OIDC-Provider-ID>:aud": "sts.amazonaws.com"
        }
}
```
Indeed it didn't work for me until I'd added the two condition values above. Rather than setting it up incorrectly to begin with and needing a troubleshooting document to fix it, the documentation should be correct from the start.

**Comment by jimdial-aws** [comment]
Please let me know what didn't work for you. Did you receive a specific error, and if so, from what source? 

Despite what the troubleshooting article states, I've set this up several times and it has always worked for me without the `aud` line. Thanks.

**Comment by ohookins** [comment]
In the end it was user error, but I think the unfamiliarity that most users will face when setting this stuff up can lead to the same thing. In my case I had an extraneous `:aud` at the end of the OIDC issuer ARN earlier in the policy document. When you don't really understand the structure of the OIDC integration all of these terms end up being quite opaque.

I have no doubt that lacking the `:aud` condition would still allow it to work - that's one less condition to check which just makes the policy less strict. Ideally there'd be just one "best" way of setting this up that is quoted verbatim in the documentation. No "edit this field to this other value", and later "replace this line with this other one". Just a simple instruction to create the role using default settings, then a single block of assume role policy which users can copy and paste in and splice in their account IDs and issuer tokens.

Hope that explains it.

**Comment by jimdial-aws** [comment]
Thanks for the response. I've updated the document. It now has the `aud` and `sub` lines, and says to change your OIDC ID and AWS Region code for both lines now. Hopefully that is more clear.

Thanks for using Amazon EKS.
