### ISSUE TITLE
Wrong URL in update instructions for old versions

### ISSUE THREAD

**Issue by fubar** [awsdocs/amazon-eks-user-guide#528]
The update instructions at https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/managing-vpc-cni.md#-manifest- say "You should only update one minor version at a time". EKS clusters that have been running for 2+ years may still be on a CNI version before 1.6 (e.g. 1.5.5 on an EKS cluster that originally ran version 1.17).

The provided URL to download file `aws-k8s-cni.yaml` only goes back to 1.7: https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.6/config/master/aws-k8s-cni.yaml does not exist.

Version 1.6 can instead be found at the previous, versioned URL: https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.6/config/v1.6/aws-k8s-cni.yaml

The docs should include a note for this.

**Comment by fubar** [comment]
In fact, the URL is only valid for CNI versions 1.9 and later. Using the new URL for versions 1.8 or 1.7 results in an "image not found" error:

https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.8/config/master/aws-k8s-cni.yaml

> Failed to pull image "602401143452.dkr.ecr.eu-west-1.amazonaws.com/amazon-k8s-cni-init:latest": rpc error: code = Unknown desc = Error response from daemon: manifest for 602401143452.dkr.ecr.eu-west-1.amazonaws.com/amazon-k8s-cni-init:latest not found: manifest unknown: Requested image not found

https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.8/config/v1.8/aws-k8s-cni.yaml

Succeeds

**Comment by jimdial-aws** [comment]
I've made updates to the doc to address older versions. It should publish later today. Thanks for bringing the issue to our attention.
