### ISSUE TITLE
review page title regarding prefix delegation

### ISSUE THREAD

**Issue by geoffcline** [awsdocs/amazon-eks-user-guide#541]
the page title "[Increase the amount of available IP addresses for your Amazon EC2 nodes](https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/cni-increase-ip-addresses.md)" may be confusing. 

Is this expanding the number of IP addresses available on your subnet, for use by EC2 instances (secondary CIDR, IP exhaustion)? or expanding the number of IP addresses available to a single instance (prefix delegation, pod density)?

**Comment by jimdial-aws** [comment]
The latter. The former is addressed in https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html#vpc-increase-ip-addresses.
