### ISSUE TITLE
Which kube-proxy version for 1.13?

### ISSUE THREAD

**Issue by Pharb** [awsdocs/amazon-eks-user-guide#55]
What is the currently recommended kube-proxy version for EKS 1.13? Is it 1.13.7, 1.13.8 or 1.13.10?

This commit updated the recommended version to 1.13.8 (https://github.com/awsdocs/amazon-eks-user-guide/commit/165a747ee2d8aa5e711a6cac42b3cd3534daba21) but it was reset to 1.13.7 by (https://github.com/awsdocs/amazon-eks-user-guide/commit/4f191285363e62cae4f94cbe87f7b30914f2242b). Not sure if that was intentional?

Also the current K8s version for EKS 1.13 is 1.13.10 so maybe that should also be used for kube-proxy?

**Comment by nrdlngr** [comment]
Thanks for your question. Yes, at this time, Amazon EKS 1.13 clusters should use the 1.13.10 version of kube-proxy from our Amazon ECR repository. I'll update the docs now to reflect this recent change.
