### ISSUE TITLE
update docs for eksctl support for Local Zones

### ISSUE THREAD

**Issue by svennam92** [awsdocs/amazon-eks-user-guide#562]
Docs here need to be updated once eksctl launches support for local zones (currently in preview):
https://docs.aws.amazon.com/eks/latest/userguide/local-zones.html
> You can't create managed node groups in AWS Local Zones with Amazon EKS. You must create self-managed nodes using the Amazon EC2 API or AWS CloudFormation. Do not use eksctl to create your cluster or nodes in Local Zones. For more information, see [Self-managed nodes](https://docs.aws.amazon.com/eks/latest/userguide/worker.html).

eksctl has added support for Local Zones (https://github.com/weaveworks/eksctl/pull/5187). This feature is currently in preview, and should be updated once the feature is released:
https://github.com/weaveworks/eksctl/releases

**Comment by pgasca** [comment]
Thank you for the alert @svennam92! I've made updates accordingly since it should now be available in eksctl public release. The public EKS user guide update should be live in a few hours.
