### ISSUE TITLE
EFS CSI with static method documentation update

### ISSUE THREAD

**Issue by tomiszili** [awsdocs/amazon-eks-user-guide#569]
Hello,

Please update the EFS CSI static deployment section.
There ara differences between the efs-csi github example and EKS documentation page.
https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/examples/kubernetes/static_provisioning/README.md

**Comment by pgasca** [comment]
The reason for the differences between the page you are pointing to is because the EKS User Guide is using multiple_pods/specs/pv.yaml. It seems to match that, just with a different fs value to demonstrate replacing it with a different value based on output.
