### ISSUE TITLE
efs-csi missing role and service account 

### ISSUE THREAD

**Issue by ranrubin** [awsdocs/amazon-eks-user-guide#571]
I've been trying to use version `2.2.6` helm chart of [aws-efs-csi-driver](https://github.com/kubernetes-sigs/aws-efs-csi-driver) (latest) and as opposed to what appears on the documentation, creating an IAM role for the `efs-csi-controller-sa` service account is not enough.  
It seems that one should create an additional IAM role to be annotated to the `efs-csi-node-sa` service account as well. 
I would happily create a PR with fixed documentation, but before putting in the work I would like your confirmation that the current documentation is indeed not complete.

**Comment by pgasca** [comment]
@ranrubin, I can confirm that the EFS CSI page could use updates. Thank you for offering to create a PR!

**Comment by pgasca** [comment]
A missing annotation step was added with this PR:
https://github.com/awsdocs/amazon-eks-user-guide/pull/621/files
