### ISSUE TITLE
EC2 VPC Endpoint is missing in Private Cluster Requirements Doc

### ISSUE THREAD

**Issue by dumlutimuralp** [awsdocs/amazon-eks-user-guide#582]
EC2 VPC Endpoint is missing from the table in the **_Considerations_** section of the [Private cluster requirements](https://docs.aws.amazon.com/eks/latest/userguide/private-clusters.html) page of Amazon EKS User Guide. 

I verified that if EC2 VPC endpoint is missing then EKS nodes are unable to connect to the EKS API. 

I also noticed that the [previous version of the same document](https://github.com/awsdocs/amazon-eks-user-guide/blob/9777ee24b89f3b44ea8f6c24543fac2f25f4cc4a/doc_source/private-clusters.md#vpc-endpoints-for-private-clusters) had EC2 listed.

**Comment by jimdial-aws** [comment]
I've added the endpoint. It will publish later today. Thanks for your input and for using Amazon EKS.
