### ISSUE TITLE
EKS connection

### ISSUE THREAD

**Issue by lesh3000** [awsdocs/amazon-eks-user-guide#589]
Hi,
I am following this tutorial: https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html
However after the config file is updated I am getting error on the kubectl get svc command

error: error loading config file "/Users/........./.kube/config": no kind "ConfigMap" is registered for version "v1" in scheme "vendor/k8s.io/client-go/tools/clientcmd/api/latest/latest.go:50"

many thanks

**Comment by jimdial-aws** [comment]
Sorry to hear that you're having issues. Did you try using the automatic or manual config instructions? A few things to confirm:
* That kubectl is installed based on these [instructions](https://docs.aws.amazon.com/eks/latest/userguide/install-kubectl.html).
* That you have the [aws-auth ConfigMap](https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html#aws-auth-configmap) installed for your cluster.
Hopefully between these additional documents you'll be able to resolve your issue.

Thanks for using Amazon EKS.
