### ISSUE TITLE
Typo in link for removing vpc-admission-webhook

### ISSUE THREAD

**Issue by cparik** [awsdocs/amazon-eks-user-guide#597]
There is a typo in the *step 2* -> *kubectl on macOS or Windows* of the **[Removing legacy Windows support from your data plane](https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html#remove-windows-support-data-plane)**. 

The link in the command is malformed. 
`kubectl delete -f https://s3.us-west-2.amazonaws.com/amazon-eks//manifests/region-code/vpc-admission-webhook/latest/vpc-admission-webhook-deployment.yaml`

**Comment by jimdial-aws** [comment]
Closing due to duplicate of https://github.com/awsdocs/amazon-eks-user-guide/pull/598.
