### ISSUE TITLE
incorrect OTEL_EXPORTER_OTLP_ENDPOINT in sample-app.yaml 

### ISSUE THREAD

**Issue by ThaiDangFr** [awsdocs/amazon-eks-user-guide#601]
I needed to change it to http://my-collector-xray-collector:4317 instead of http://my-collector-collector:4317
to make it work with xray
and also because my-collector-collector was not found (sample-app pod logs)

**Comment by pgasca** [comment]
This wasn't the right spot for your request. Please target the applicable repos in the future. I've created a PR on your behalf:
https://github.com/aws-observability/aws-otel-community/pull/446
