### ISSUE TITLE
Deploy the Amazon EBS CSI Driver command's GitHub link expired.

### ISSUE THREAD

**Issue by abhilash-thumma** [awsdocs/amazon-eks-user-guide#61]
Deploy the Amazon EBS CSI Driver commands GitHub link expired. It is now updated with kustomization.yaml.

kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master"

The document needs to be updated with the new steps

**Comment by nrdlngr** [comment]
I'm not sure I understand your request. I ran the CSI driver deployment command and it worked fine for me. Can you elaborate on what you think needs to be changed in this doc?

**Comment by nrdlngr** [comment]
On 10/24, I added a note to this topic that `kubectl` version 1.14 or greater is required for this command.

**Comment by abhilash-thumma** [comment]
Thank you @nrdlngr for looking into this. I was able to fix the issue on my cluster. It is working for me now.

Will close the issue.

**Comment by abhilash-thumma** [comment]
Closed
