### ISSUE TITLE
Unclear Documentation of Default Roles

### ISSUE THREAD

**Issue by danielburn5** [awsdocs/amazon-eks-user-guide#628]
# Problem
[doc_source/default-roles-users.md](https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/default-roles-users.md) is not clear about what roles are provided by default.

Not all of the resources listed in the roles section are regular roles. Some of them are cluster roles. 

Furthermore, I find there to be many more roles and cluster roles created with an `eks:` prefix when I build a clean EKS cluster which are not mentioned in the documentation... should they be? Or am I mistaken?

Details below.

### Roles
These exist in the documentation and are correctly referenced as roles.
+ `eks:authenticator`
+ `eks:certificate-controller`
+ `eks:k8s-metrics`

### Cluster Roles
These exist in the documentation and are incorrectly referenced as roles. These are cluster roles.
+ `eks:certificate-controller-approver`
+ `eks:cluster-event-watcher`
+ `eks:fargate-scheduler`
+ `eks:nodewatcher`
+ `eks:pod-identity-mutating-webhook`

## Missing Roles
These roles appear in my EKS cluster after a clean build but are not mentioned in the documentation.
+ `eks:addon-manager`
+ `eks:fargate-manager`

## Missing Cluster Roles
These cluster roles appear in my EKS cluster after a clean build but are not mentioned in the documentation.
+ `eks:addon-manager`
+ `eks:certificate-controller-signer`
+ `eks:cloud-controller-manager`
+ `eks:cloud-provider-extraction-migration`
+ `eks:fargate-manager`
+ `eks:k8s-metrics`
+ `eks:node-bootstrapper`
+ `eks:node-manager`
+ `eks:podsecuritypolicy:privileged`
+ `eks:tagging-controller`

## Versions
Incase it's useful:
```shell
~/dev/ ❯ kubectl version                                                                                                                                   11:07:37
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:30:48Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.15-eks-fb459a0", GitCommit:"be82fa628e60d024275efaa239bfe53a9119c2d9", GitTreeState:"clean", BuildDate:"2022-10-24T20:33:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by danielburn5** [comment]
Looking again, I also see some EBS related Cluster Role Bindings:
```
clusterrolebinding.rbac.authorization.k8s.io/ebs-csi-attacher-binding
clusterrolebinding.rbac.authorization.k8s.io/ebs-csi-node-getter-binding
clusterrolebinding.rbac.authorization.k8s.io/ebs-csi-provisioner-binding
clusterrolebinding.rbac.authorization.k8s.io/ebs-csi-resizer-binding
clusterrolebinding.rbac.authorization.k8s.io/ebs-csi-snapshotter-binding
```

And Roles...
```
clusterrole.rbac.authorization.k8s.io/ebs-csi-node-role
clusterrole.rbac.authorization.k8s.io/ebs-external-attacher-role
clusterrole.rbac.authorization.k8s.io/ebs-external-provisioner-role
clusterrole.rbac.authorization.k8s.io/ebs-external-resizer-role
clusterrole.rbac.authorization.k8s.io/ebs-external-snapshotter-role
```

I guess these should be documented too?

**Comment by danielburn5** [comment]
In another build, I am seeing a ClusterRoleBinding called `eks:addon-cluster-admin`. Looks like this comes from EKS too?

**Comment by danielburn5** [comment]
@jimdial-aws Do you have an idea when this issue might be reviewed?

**Comment by jimdial-aws** [comment]
Sorry for the confusion. I've rewritten this topic to avoid this situation in the future. The document now explains how to view the identities on your cluster using the AWS Management Console or kubectl. It also helps you identify which identities that you see were created by Amazon EKS. 

The EBS CSI driver isn't installed by default on Amazon EKS clusters, so isn't addressed in the document, but the document does now state that when you install optional add-ons, the add-on may add additional identities. To determine whether an add-on adds additional identities, see the documentation for the add-on.

Thanks for the feedback and for using Amazon EKS.
