### ISSUE TITLE
Update Calico documentation

### ISSUE THREAD

**Issue by jayanthvn** [awsdocs/amazon-eks-user-guide#638]
Update calico documentation (https://docs.aws.amazon.com/eks/latest/userguide/calico.html) to include ANNOTATE_POD_IP optimization when calico is used with EKS and not on Ipv6 support with calico

Ipv4 optimization -> 
Ref : https://github.com/aws/amazon-vpc-cni-k8s#annotate_pod_ip-v193

CNI 1.9.3 onwards, Setting ANNOTATE_POD_IP to true will allow IPAMD to add an annotation vpc.amazonaws.com/pod-ips to the pod with pod IP.

There is a known https://github.com/kubernetes/kubernetes/issues/39113 with kubelet taking time to update Pod.Status.PodIP leading to calico being blocked on programming the policy. Setting ANNOTATE_POD_IP to true will enable AWS VPC CNI plugin to add Pod IP as an annotation to the pod spec to address this race condition.

To annotate the pod with pod IP, you will have to add "patch" permission for pods resource in aws-node clusterrole.

```
cat << EOF > append.yaml
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - patch
EOF
```
```
kubectl apply -f <(cat <(kubectl get clusterrole aws-node -o yaml) append.yaml)
```

EKS Ipv6 with Calico ->

Ipv6 is not yet supported with Calico - https://github.com/aws/containers-roadmap/issues/1871

**Comment by jimdial-aws** [comment]
I've incorporated this into the doc. Thank you for your contribution.
