### ISSUE TITLE
Update AutoScaling page IAM policy for cluster-autoscaler for EKS >=1.23 cluster 

### ISSUE THREAD

**Issue by angelaaaaaaaw** [awsdocs/amazon-eks-user-guide#646]
For EKS cluster >= 1.23 version, when set the image from github that matches the Kubernetes version, pod is in crushloopbackoff status, due to extra ec2:DescribeInstanceTypes IAM permission is needed. 

From cluster auto scaling pod log without ec2:DescribeInstanceTypes IAM permission for the iam role attached:

`F1216 12:58:20.618773       1 aws_cloud_provider.go:386] Failed to generate AWS EC2 Instance Types: UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: 0624faae-4e59-442c-8baf-58573926b340
`

After adding the extra permission, pod in running status after restart, hence please update the IAM policy page to include above permission. 

Proposed IAM policy

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "autoscaling:SetDesiredCapacity",
                "autoscaling:TerminateInstanceInAutoScalingGroup"
            ],
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "aws:ResourceTag/k8s.io/cluster-autoscaler/my-cluster": "owned"
                }
            }
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:DescribeAutoScalingGroups",
                "ec2:DescribeLaunchTemplateVersions",
                "ec2:DescribeInstanceTypes",
                "autoscaling:DescribeTags",
                "autoscaling:DescribeLaunchConfigurations"
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by JazkyAWS** [comment]
Closing out as this was addressed earlier this year.
