### ISSUE TITLE
Proxy Protocol annotation in K8s in AWS fail to enable in AWS ELBv2

### ISSUE THREAD

**Issue by garymalaysia** [awsdocs/amazon-eks-user-guide#65]
Following to this [guide](https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#aws) to enable Proxy Protocol on AWS ELBv2, but AWS ELBv2 fail to enable the attribute.

```service.beta.kubernetes.io/aws-load-balancer-proxy-protocol:'*'```

A sample value.yaml is below:

```apiVersion: v1
kind: Service
metadata:
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  name: lb
  labels:
    name: lb
spec:
  ports:
  - port: {{ .Values.simpleflask.service.ports.port }}
    targetPort: {{ .Values.simpleflask.service.ports.targetPort }}
  selector:
    run: simpleflask
  type: LoadBalancer```

**Comment by M00nF1sh** [comment]
@garymalaysia 
That annotation is only supported on AWS Classic LoadBalancer(e.g. without the `service.beta.kubernetes.io/aws-load-balancer-type: "nlb"`).

We haven't added support for proxyProtocolV2 for Kubernetes-NLB support, will track it as an action item.

**Comment by nrdlngr** [comment]
This work item is being tracked internally. Closing issue.
