### ISSUE TITLE
EBS CSI driver doc outdated

### ISSUE THREAD

**Issue by eljeffeg** [awsdocs/amazon-eks-user-guide#694]
The directions for the EBS CSI driver creation and update via the AWS Management Console is outdated and doesn't reflect the current options.  The update that adds another condition doesn't appear to conform to the directions and I'm not sure what to do next.  Please take a look and update if possible.
https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/csi-iam-role.md#-aws-management-console-

**Comment by pgasca** [comment]
I did some minor rewrites to enhance clarity which may help reduce confusion. I tested the procedure and the options are valid.  If you are seeing different options, please give more specific details.
