### ISSUE TITLE
"Application load balancing on Amazon EKS" Doc Has Misformatted Link

### ISSUE THREAD

**Issue by zacharylayne** [awsdocs/amazon-eks-user-guide#697]
On line 31, 
`[https://github.com/kubernetes-sigs/aws-load-balancer-controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller)`
should be changed to something like:
`[AWS Load Balancer Controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller)`

Keep in mind the link points to a GitHub repo.

**Comment by jimdial-aws** [comment]
This has been fixed.
