### ISSUE TITLE
Failing to communicate with API server: Get https://172.20.0.1:443/api/v1/componentstatuses?timeout=30s: waiting for cluster agent to connect

### ISSUE THREAD

**Issue by nandeeshb09** [awsdocs/amazon-eks-user-guide#70]
Recently we have upgraded eks cluster from eks v1.11 to v1.12 version , post upgrade we are getting error communicating with api server intermittently.

Please help here to fix this issue,as we are facing our services are going down intermittently.

amazon cni version -- 1.5.3
core dns -- 1.2.2
kube proxy -- 1.12.6

**Comment by azavrin-myvest** [comment]
same here

**Comment by jimdial-aws** [comment]
Sorry for the delayed response. I hope your issue has been resolved. If not, I recommend opening a case with support to help determine the problem. Thank you for using Amazon EKS.
