### ISSUE TITLE
K8s manifest to create secrets for service accounts not working

### ISSUE THREAD

**Issue by berry2012** [awsdocs/amazon-eks-user-guide#711]
This refers to action 3 in step 2 of the Tutorial: Deploy the Kubernetes Dashboard (web UI) [documentation](https://docs.aws.amazon.com/eks/latest/userguide/dashboard-tutorial.html)

2 issues 
- The manifest is not properly indented
- The manifest file name is wrong leading to the kubernetes object not being created eventually

```
error: error when retrieving current configuration of:
Resource: "/v1, Resource=secrets", GroupVersionKind: "/v1, Kind=Secret"
Name: "", Namespace: "default"
from server for: "eks-admin-service-account-secret.yaml": resource name may not be empty
```

```
serviceaccount/eks-admin unchanged
clusterrolebinding.rbac.authorization.k8s.io/eks-admin unchanged
```

**Comment by JazkyAWS** [comment]
Closing this issue as Dashboard was deprecated from the EKS UG.
