### ISSUE TITLE
VPC CNI Add-on version not matching with the real deployed one

### ISSUE THREAD

**Issue by mariomerco** [awsdocs/amazon-eks-user-guide#717]
Hello! Seems like the versions of the add-on doesn't match what the EKS Console is saying and what the actual pod has as the image.

Image of the add-on version showing `eksbuild.2`:
<img width="931" alt="image" src="https://user-images.githubusercontent.com/7386479/233384461-d48c1234-285d-4377-8ee2-412c7080bea7.png">

Image of the actual pod deployed showing `eksbuild.1`:
<img width="949" alt="image" src="https://user-images.githubusercontent.com/7386479/233384299-cc476e62-2145-4ee2-8de4-fc9a7b29dbcd.png">

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
