### ISSUE TITLE
scaling out, not up

### ISSUE THREAD

**Issue by pmerson** [awsdocs/amazon-eks-user-guide#731]
The introduction in the [Autoscaling web page](https://docs.aws.amazon.com/eks/latest/userguide/autoscaling.html) says "Autoscaling is a function that automatically scales your resources up or down..."
 
However, this service provides **horizontal** scalability, not **vertical scalability**.  The correct phrase would be "Autoscaling is a function that automatically scales your resources out and in..."

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
