### ISSUE TITLE
RBAC link in cluster endpoint doc doesn't work

### ISSUE THREAD

**Issue by vhryshchenko-source** [awsdocs/amazon-eks-user-guide#733]
Amazon EKS cluster endpoint access control (https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html).
Link on [Role Based Access Control](https://kubernetes.io/docs/admin/authorization/rbac/) (RBAC) doesn't work. 
Looks like the link is no longer up to date and should be used this: https://kubernetes.io/docs/reference/access-authn-authz/rbac/

**Comment by jimdial-aws** [comment]
Thanks for letting us know. I've fixed this. The change will publish soon.
