### ISSUE TITLE
Pod Security Policies feature removed

### ISSUE THREAD

**Issue by mathieu-clnk** [awsdocs/amazon-eks-user-guide#740]
The [update cluster](https://github.com/awsdocs/amazon-eks-user-guide/blob/8404ab6028185f6ef8dc5382e738caa5698c2e07/doc_source/update-cluster.md?plain=1#L38) documentation specifies a step which is no longer needed in Kubernetes 1.25 and later versions as the feature has been removed.

**Comment by pgasca** [comment]
Thank you for submitting a PR:
https://github.com/awsdocs/amazon-eks-user-guide/pull/741

An issue isn't needed as well when a PR is submitted. Closing this as duplicate.
