### ISSUE TITLE
Question: how the iam-role + service account working under the cover

### ISSUE THREAD

**Issue by WeihanLi** [awsdocs/amazon-eks-user-guide#756]
Hi team, thanks for providing the great docs.
I have a question about using the `iam-role` + service account following the docs on

- https://docs.aws.amazon.com/eks/latest/userguide/associate-service-account-role.html
- https://docs.aws.amazon.com/eks/latest/userguide/pod-configuration.html

It works now, but want to learn more deeply, how does it work?

How is the token generated and kept updated? Is there any more document about it?

Thanks very much

**Comment by chrisnegus** [comment]
Here are a couple of other link that you might find interesting:

* https://eksctl.io/usage/iamserviceaccounts/
* https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/

Is there anything in particular you would like to know that we could add to the EKS user guide?

**Comment by WeihanLi** [comment]
@chrisnegus thanks very much, it does help me. We're using this way on eks now, it helps me understand how it works in depth, think it would be better to add more docs like these and better to add links on the eks documentation page
