### ISSUE TITLE
cluster-autoscaler-autodiscover.yaml is using an old version of cluster-autoscaler

### ISSUE THREAD

**Issue by omerfsen** [awsdocs/amazon-eks-user-guide#76]
On current documentation at https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html we use following command:

kubectl apply -f https://raw.githubusercontent.com/kubernetes/autoscaler/master/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml

This yaml file used an old version of cluster-autoscaler (currently the one supports kubernetes v1.12)

https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/cluster-autoscaler?gcrImageListsize=30 show the latest  docker images

So I think documentation needs to be updated to reflect to use the same major version of cluster-autoscaler that matches the major version of the kubernetes cluster we create.

For example we have 1.14.7 of it now https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/cluster-autoscaler@sha256:86ae2c68bdebbfeb5ac73ebe6bef790da6d8e9b4d186852f016f0a46355cd21d/details?tab=info

**Comment by jaypipes** [comment]
Hi @omerfsen! I've submitted a PR to upstream Kubernetes autoscaler to update the image in that YAML file accordingly: https://github.com/kubernetes/autoscaler/pull/2838

**Comment by jimdial-aws** [comment]
Closing since the doc will continue to reference the file currently referenced.
