### ISSUE TITLE
metric server installation script fails (curl , jq)

### ISSUE THREAD

**Issue by omerfsen** [awsdocs/amazon-eks-user-guide#77]
On https://docs.aws.amazon.com/eks/latest/userguide/metrics-server.html 
it says 

```
DOWNLOAD_URL=$(curl -Ls "https://api.github.com/repos/kubernetes-sigs/metrics-server/releases/latest" | jq -r .tarball_url)
DOWNLOAD_VERSION=$(grep -o '[^/v]*$' <<< $DOWNLOAD_URL)

```

but 

curl -Ls "https://api.github.com/repos/kubernetes-sigs/metricsserver/releases/latest"
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/repos/releases/#get-the-latest-release"
}

does not return tarball_url  so script fails

**Comment by ashwanijha04** [comment]
Use **'metrics-server**' instead of '**metricsserver'**.

This works:
`curl -Ls "https://api.github.com/repos/kubernetes-sigs/metrics-server/releases/latest"`

**Comment by omerfsen** [comment]
It seems copying from pdf file it removes '-' character...

**Comment by omerfsen** [comment]
The pdf guide contains - character but when you copy from pdf it removes - character.
