### ISSUE TITLE
Default behaviour of cluster upgrade policy is not clear

### ISSUE THREAD

**Issue by badrish-s** [awsdocs/amazon-eks-user-guide#782]
In https://docs.aws.amazon.com/eks/latest/userguide/view-upgrade-policy.html, below statements are confusing for the reader

One of the sentence says below:
"Extended support is enabled by default for new clusters, and existing clusters. You can view if extended support is enabled for a cluster in the AWS Management Console, or by using the AWS CLI."

The very next sentance says below:
"If you want your cluster to stay on its current Kubernetes version to take advantage of the extended support period, you must enable the extended support upgrade policy before the end of standard support period."

If Extended support is the default behavior, then why is it highlighted and important to enable the extended support upgrade policy before the end of standard support period?

Blocking users from changing the value for Upgrade policy after standard support period makes sense, but IMO the default behavior of cluster upgrade policy is not being coming out rightly in the documentation. 

Maybe below will do it better?

"If you have changed the default behaviour and set 'Upgrade policy=Standard' but want to switch back to 'Upgrade policy=Extended', you must do that before the end of standard support period."

**Comment by geoffcline** [comment]
discussed in slack, suggested changes saved in source file
