### ISSUE TITLE
Incorrect kube-proxy Version for 1.30 in doc

### ISSUE THREAD

**Issue by sathakatheef** [awsdocs/amazon-eks-user-guide#790]
Hi Team
The doc [here](https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html) says available kube-proxy image for k8s version 1.30 is `v1.30.3-eksbuild.3` but in our environment we are getting this when rolling it out `Error: failed to fetch addon version: no version(s) found matching "v1.30.3-eksbuild.3" for "kube-proxy"`.

When checking using eksctl looks like the latest available kube-proxy version for k8s v1.30 is `v1.30.3-eksbuild.2` as below
```
$ eksctl utils describe-addon-versions --kubernetes-version 1.30 --name kube-proxy --region ap-southeast-2 --profile <profile_name> | grep AddonVersion
			"AddonVersions": [
					"AddonVersion": "v1.30.3-eksbuild.2",
					"AddonVersion": "v1.30.0-eksbuild.3",
					"AddonVersion": "v1.30.0-eksbuild.2",
					"AddonVersion": "v1.29.7-eksbuild.2",
					"AddonVersion": "v1.29.3-eksbuild.5",
					"AddonVersion": "v1.29.3-eksbuild.2",
					"AddonVersion": "v1.29.0-eksbuild.1",
					"AddonVersion": "v1.28.12-eksbuild.2",
					"AddonVersion": "v1.28.8-eksbuild.5",
					"AddonVersion": "v1.28.8-eksbuild.2",
					"AddonVersion": "v1.27.16-eksbuild.3",
					"AddonVersion": "v1.27.16-eksbuild.2",
					"AddonVersion": "v1.27.12-eksbuild.5",
					"AddonVersion": "v1.27.12-eksbuild.2",
```

Can it be double checked please? and update accordingly. Thanks. (this looks to be the source [PR](https://github.com/awsdocs/amazon-eks-user-guide/commit/a0d4e6bdf9da3a85b29aa7241b4a39abfb7cb09b#diff-69601eea2613fca7a45e5e9925ab3f1de3c6a51ba695946f86a9ac6cf86f86f4))

**Comment by fincd-aws** [comment]
Hey, I caught up the kueb-proxy add-on version and container image versions, and I will use the `aws eks describe-addon-versions` to regularly catch missed versions in the future.
