### ISSUE TITLE
An error occurred (UnsupportedAvailabilityZoneException) when calling the CreateCluster operation: Cannot create cluster 'rotha-dev-devel' because us-east-1c, the targeted availability zone, does not currently have sufficient capacity to support the cluster.

### ISSUE THREAD

**Issue by RothAndrew** [awsdocs/amazon-eks-user-guide#8]
I've been following the AWS EKS Getting Started Guide to the letter, and when trying to run the `aws eks create-cluster` step I am receiving the following error:

> An error occurred (UnsupportedAvailabilityZoneException) when calling the CreateCluster operation: Cannot create cluster 'rotha-dev-devel' because us-east-1c, the targeted availability zone, does not currently have sufficient capacity to support the cluster. Retry and choose from these availability zones: us-east-1a, us-east-1b, us-east-1d

How do I specify which availability zone the cluster will be deployed to? If I'm understanding correctly, the chosen AZ is specified when creating the VPC.

The amazon-eks-vpc-sample.yaml file used has the following section in it:

```
AvailabilityZone:
        Fn::Select:
        - '0'
        - Fn::GetAZs:
            Ref: AWS::Region
```
This is repeated 3 times, one for each Subnet. The only change is the `'0'` gets changed to `'1'` and `'2'`. I'm guessing the change needs to go here, but I have no idea what needs to be put there instead.

**Comment by nrdlngr** [comment]
The VPC template creates subnets in 3 AZs. You specify the subnets when you create the EKS cluster.

You must specify at least 2 subnets, so specify 2 of the subnets that are in the supported AZs in your error message.

**Comment by NisarTahir** [comment]
I got the same error using:

`aws eks create-cluster --name eks-cluster --role-arn arn:aws:iam::123456789:role/eksServiceRole --resources-vpc-config subnetIds=subnet-adf123,subnet-e512b456,subnet-cbd37789,securityGroupIds=sg-51234567`

Cloud Formation creates the 3rd subnet (eks-vpc-Subnet03) in us-east-1c.
I deleted that subnet and created the subnet again (eks-vpc-Subnet03) in us-east-1d

The cluster can now be created

**Comment by bchav** [comment]
EKS is currently only available in a subset of us-east-1 availability zones. 

For all accounts, us-east-1a, 1b, 1c, and 1d are randomized across accounts. However, despite this randomization, EKS is always available in 3 of these 4 AZs. 

EKS will be expanding into additional zones in us-east-1 this year.
