### ISSUE TITLE
Periodic updated removed "EKS Pod Identity restrictions"

### ISSUE THREAD

**Issue by timmles** [awsdocs/amazon-eks-user-guide#801]
Hi,

There was a periodic update "Periodic update - 2024/09/26- 4:09pm PDT" that removed a section of the docs "EKS Pod Identity restrictions".
https://github.com/awsdocs/amazon-eks-user-guide/commit/69e3c0c81eaebf370e91e51fd757ec6c1d6c6530

I believe this was done in error, but perhaps I'm missing something.
I'm happy to submit a PR, but I don't want to suggest rolling back someones changes without context.

P.S. the specific issue I'm chasing down was that EKS Pod Identity is not supported on Fargate - which was specified the snippet that was deleted - i.e. the current docs don't describe this limitation.

**Comment by geoffcline** [comment]
Thank you for this feedback -- this content was removed from the docs due to inaccuracies. I am currently working on revised docs.
