### ISSUE TITLE
Create a service account for the ALB ingress controller fails

### ISSUE THREAD

**Issue by tde908** [awsdocs/amazon-eks-user-guide#83]
The docs for https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html 

issue: 
Step 4: Create a service account for the ALB ingress controller and attach the policy to the service account.

If you do not create your cluster with eksctl and you run the command in step 4:

eksctl create iamserviceaccount \
    --region us-east-1 \
    --name alb-ingress-controller \
    --namespace kube-system \
    --cluster prod \
    --attach-policy-arn arn:aws:iam::111122223333:policy/ALBIngressControllerIAMPolicy \
    --approve

It will throw the error: 

no eksctl-managed CloudFormation stacks found for "cluster_name". 

To reproduce the error: 
1. create a cluster via the console and attach unmanaged linux worker nodes
2. follow the steps in: https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html

Issue 2: 

When selecting the link "Edit this page on GitHub" the docs appear to be out of sync.

**Comment by tde908** [comment]
Docs have been updated and now provide options for eksctl, console and cli. 
Closing the issue as it is resolved.

**Comment by spirit986** [comment]
@tde908 what did you do to resolve this?

**Comment by lokey** [comment]
This error was resolved for me when I upgraded eksctl version from `0.30.0` to `0.32.0`
