### ISSUE TITLE
Metrics-server installation via Helm

### ISSUE THREAD

**Issue by aliusmiles** [awsdocs/amazon-eks-user-guide#98]
Maybe add a Helm [chart](https://github.com/helm/charts/tree/master/stable/metrics-server) for metrics-server installation instead or as an alternative to curl & jq? Similarly to Prometheus installation instructions.

P.S. I could submit a PR if needed.

**Comment by jimdial-aws** [comment]
Thanks for the feedback. The document has been updated to just apply a manifest to install the metrics server now. No curl or jq anymore.
